### ISSUE TITLE
Modified the Queries

### ISSUE THREAD

**Issue by andyhehk** [bigframeteam/BigFrame#2]
Currently, tweets are filtered by the product ids, but it comes more natural to filter them by the actual product name. Besides, it make nonsense to join the item Table in the relational-only query if we do not use the product name. 

Suggestions:
(1) Select both i_item_sk and i_product_name in the final result of the relational part
(2) Filter the tweets by the product_name obtained in part (1)

Actually, in the generated tweets, the product_name has already been attached on the "hash_tags" field.

**Comment by mayureshkunjir** [comment]
I didn't know that product name appears in hash_tags. It certainly makes more sense to use it instead of extracting product id from the tweet text. Let's remove product id from text as well and just use product name in hash tags.
