### ISSUE TITLE
Push failed for the branch "workflow"

### ISSUE THREAD

**Issue by andyhehk** [bigframeteam/BigFrame#5]
Hi all,

I encountered conflict when I tried to push my code to the branch "workflow". It seems that someone and I are modifying the same codes at the same time. I want to resolve the conflict, and it needs to delete some files. 

Advise: If we want to make some changes on the same branch next time, can we synchronize with each other first?

**Comment by ghost** [comment]
Sorry about your inconvenience. From the next time, I will let you know about the change before I push to the repository.
