### ISSUE TITLE
Change the initiator of the kronecker graph generator

### ISSUE THREAD

**Issue by andyhehk** [bigframeteam/BigFrame#9]
The original initiator is a 10_10 matrix, which make the graph size increase in 10^2 manner. We'd better change it to 2_2 matrix. For two reasons:
(1) I just found 2*2 is more prevalent in kronecker graph generator
(2) The graph size can achieve finer control

I'm sorry that I make a wrong choice at the beginning. I will commit the changes to the workflows branch. Latter experiment should adopt the new generator.

**Comment by andyhehk** [comment]
The code has committed to branch 'workflows'.

**Comment by mayureshkunjir** [comment]
Hey Andy, I have merged all changes from 'workflows' and '0.2' to 'master' branch except this one. You could merge new changes to master directly (including this change).

**Comment by andyhehk** [comment]
OK, I will do the merge.

On Mon, Oct 28, 2013 at 11:01 PM, Mayuresh Kunjir
notifications@github.comwrote:

> Hey Andy, I have merged all changes from 'workflows' and '0.2' to 'master'
> branch except this one. You could merge new changes to master directly
> (including this change).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bigframeteam/BigFrame/issues/9#issuecomment-27218873
> .

## 

~Andy
